---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: database-service/database-service
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: database-service
  name: database-service-subscription-1
  namespace: bank-infra
spec:
  channel: bank-infra/database-service-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: database-service-placement-1
