clusterNames:
  - aws-cluster-shared-0
  - aws-cluster-shared-1
  - aws-cluster-shared-2

infrastructure: ${infrastructure}  

global_base_domain: ${global_base_domain}  


cockroachdb:
  image:
    repository: cockroachdb/cockroach
    tag: "v21.1.7"
    # repository: cockroachdb/cockroach-unstable
    # tag: "v21.1.0-rc.2"    
  storage:
    persistentVolume:
      storageClass: cockroachdb
  cluster: ${cluster}
  uid: ${uid}
  conf:
    cache: 8GiB
    max-sql-memory: 8GiB
    join: 
      - cockroachdb-0.aws-cluster-shared-0.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-1.aws-cluster-shared-0.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-2.aws-cluster-shared-0.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-0.aws-cluster-shared-1.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-1.aws-cluster-shared-1.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-2.aws-cluster-shared-1.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-0.aws-cluster-shared-2.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-1.aws-cluster-shared-2.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-2.aws-cluster-shared-2.cockroachdb.cockroachdb.svc.clusterset.local            
  fullnameOverride: cockroachdb
  statefulset:
    replicas: 3
    tolerations:
      - key: "workload"
        operator: "Equal"
        value: "cockroach"
        effect: "NoSchedule"
    nodeSelector:
      workload: cockroach    
    # podAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #     - weight: 100
    #       podAffinityTerm:
    #         labelSelector:
    #           matchLabels:
    #             app.kubernetes.io/component: cockroachdb
    #             app.kubernetes.io/instance: cockroachdb
    #             app.kubernetes.io/name: cockroachdb
    #         topologyKey: failure-domain.beta.kubernetes.io/zone

  tls:
    enabled: yes
    certs:
      provided: yes
      tlsSecret: yes
      nodeSecret: cockroachdb-tls
