---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: vault
    apps.open-cluster-management.io/git-path: bank-knative-service/bank-knative-service
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: bank-knative-service
  name: bank-knative-service-subscription-1
  namespace: bank-infra
spec:
  channel: bank-infra/bank-knative-service-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: bank-knative-service-placement-1
