---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: vault
    apps.open-cluster-management.io/git-path: user-service/user-service
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: user-service
  name: user-service-subscription-1
  namespace: bank-infra
spec:
  channel: bank-infra/user-service-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: user-service-placement-1
