apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-simulator-deployment
  labels:
    app: mobile-simulator
spec:
  selector:
    matchLabels:
      app: mobile-simulator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mobile-simulator
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: quay.io/wdovey/mobile-simulator:css-fix
          imagePullPolicy: Always
          name: mobile-simulator
          envFrom:
            - secretRef:
                name: mobile-simulator-secrets
          env:
            - name: PORT
              value: '8080'
          ports:
            - containerPort: 8080
