apiVersion: v1
data:
  OIDC_AUDIENCES: MmE5ZTM5MGYtMjA1Ni00ZGZlLWJlODktNjQzZGU1MWNjOWJm
  OIDC_ISSUERIDENTIFIER: aHR0cHM6Ly9hdS1zeWQuYXBwaWQuY2xvdWQuaWJtLmNvbS9vYXV0aC92NC8yNjRkOWVkMy0zODlhLTRjN2UtOGEwZi05NGViNzA1NGExNjA=
  OIDC_JWKENDPOINTURL: aHR0cHM6Ly9hdS1zeWQuYXBwaWQuY2xvdWQuaWJtLmNvbS9vYXV0aC92NC8yNjRkOWVkMy0zODlhLTRjN2UtOGEwZi05NGViNzA1NGExNjAvcHVibGlja2V5cw==
kind: Secret
metadata:
  name: bank-oidc-secret
  namespace: bank-infra
type: Opaque
