apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: bank-iam-secret
  namespace: bank-infra
spec:
  encryptedData:
    IAM_APIKEY: AgCoRBFITWsD1+Pi2ezeZXxc9l/rztdm5qoBzKmYHxED3cBnYWycU+xEg8I2tyW+V+iTTjlaI2SVPzwRHNHP0x+PfXQDWR6cEkKUSaHc4/gFD6dm+GYwjHu+z6s8ghNvdWvIWamb5WVGjBuhvwlzP6OLYorQ7kD8J0tgWVMnxUiDljYQxtyqde5dj9f0vn5kk4FllHl6w1kVkZ3lJZIVPYYQSmnDDKembCTxp1D0qTRsKjPUAcxyNBI9OUwHquA9YV54waD67EFMwlGzJJV2HuVmLYMRlxLmZDpzVNO9aWUrnEf6e/ND1VG/K1pcEuByHADyz5KBio+1RHvijMj5fa3U9g5ONqctuzp4dKh8rO+daLZ3eCs0IJWy8gEmBJdZRQBnaxeZrEUBaBqwPFRczxhiZyMcq4S5LKYNRjAAJnRE+n4OhWI9zk9rhrRqqKNCLcNmq3BWA/mWE8kFwQppeXkQ/l+r4cxaB1np7CvzKKpqYU0rFsxuDOawbhuWvVS4qxwHks37koA9Qt8KPgacyUflSvgGXWnB/uOXEzltJCrNBVKySukrO+b0klIuEhYKhxMCIX7ch34WMvB1Go68xJ/IE950YBsphZIIccbbLqeh4Au+pscLLsowGBDYK6in1aDODXfe4dRJuHmNk1WMJJxEMTqx7zlscLqcQ0FWoaGh8aOUUrENl5iMYwJoyjfyzTJT423Mg+Q4Ya7OZ8zU6X24FfNSBDmsT5bygB1a5f+lAokFhts7Ikhlie6Khw==
    IAM_SERVICE_URL: AgCeIKaLL4ZUCnbnVnCyCkKxSGaMw9DB0vjg4Wdt+DSAvhrp2cK3fmqAQ+jTOBmkeZdF3tjYuxoqJ3qTEnS97LGJQMFaqHdk3kzBYwgMsgP7UIa+I8Bot8xNIM4FiLmxYhnyHhIFB1sNCU9KCCuI2dmIyON74gcRQ6UReM6l3E8JSgpXbwl3lAAY+G2ppU+D8b9N4pORB2pb6esgYbloLLFvJPqOGvMRjHZoHBTWd6VXCgBbGbXCUhA0PMJAQgoh6YflODWafWj19ge6p1yIkY2Oji5IgL6OG68wv+OFaG2kQtAPdt1xempW6yAxqtebe8u/Wj/9prawpysV4LYFX8FAqnjuGd73akR3/aNagSHgM0CJokAPx55xORe/yHia6CGAmVnQm0ZO2Qg4YomVvIQTKI7tYIR8vaLga0TBpfzmn2ranhofrl4//w89n8FH/JFWZg0MOZEtiDvruMQcv0ZmONxN5Ls71Ytep3OkXETIlhZUsqwOovslhMBNeflqXL4bO/bPE3YBvaab2Xn14AA+BzSIXozZe1EbexlNQyL71nkYYA/S5hQOSn/QW85TbBThewTmBdQfnAkLwGYNoQMExPD7JDWhCWs33Rxtxl3pKxk88eN5ADT7aWYePYvPi8LO8Y3OAXfx4YrepIIKD2aUnS1PU9IZTWFfSL3Fyz9xg9x+aXQAi+HsR/YJQShEXFMzuSL/3gTBJsw0zbGV3CAzsuD+yB3XUdDwV87i3cKqSlFzHfpD/4Xa
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: bank-iam-secret
      namespace: bank-infra
    type: Opaque