apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: transaction-service
        image: quay.io/wdovey/bank-transaction-service:1.0
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 9080
        envFrom:
        - secretRef:
            name: bank-db-secret
        - secretRef:
            name: bank-oidc-secret
        env:
        - name: USER_SERVICE_URL
          value: "http://user-service:9080/bank/v1/users"
        - name: KNATIVE_SERVICE_URL
          value: "http://process-transaction.bank-infra.svc.cluster.local"
        - name: WLP_LOGGING_CONSOLE_LOGLEVEL
          value: INFO
